[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:jupyter]
command=/root/.jupyter/start-jupyter.sh
environment=MATPLOTLIBRC="/root/.config/matplotlib/.matplotlibrc"
stdout_logfile=/dev/null
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
stopasgroup=true
killasgroup=true
priority=10

[program:code-interpreter]
command=/root/.jupyter/start-code-interpreter.sh
directory=/root/.server
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
stopasgroup=true
killasgroup=true
priority=20
