name: Build Prod Template

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: Target environment (`all` = every production cluster)
        required: true
        type: choice
        default: all
        options:
          - all
          - foxtrot
          - juliett
          - tango
          - staging
      skip_cache:
        description: Skip build cache
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  build-template:
    name: Build
    uses: ./.github/workflows/build_prod_template_clusters.yml
    with:
      target: ${{ inputs.target_environment }}
      skip_cache: ${{ inputs.skip_cache }}
    secrets: inherit
