name: Build Template

on:
  workflow_call:
    secrets:
      E2B_ACCESS_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
    inputs:
      E2B_DOMAIN:
        required: false
        type: string

permissions:
  contents: read

jobs:
  build:
    name: Build Docker Image and Template
    runs-on: ubuntu-latest
    outputs:
      template_id: ${{ steps.build-template.outputs.template_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set package version
        working-directory: ./template
        run: |
          VERSION=$(cat ../chart_data_extractor/pyproject.toml | grep version | cut -d '"' -f 2)
          echo "Version: $VERSION"
          sed -i "s/e2b_charts/e2b_charts==${VERSION}/g" requirements.txt

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./template
          push: false
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/code-interpreter:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install E2B CLI
        run: npm install -g @e2b/cli

      - name: Build E2B template
        id: build-template
        run: |
          rm -f e2b.toml
          e2b template build --memory-mb 1024 -c "/root/.jupyter/start-up.sh" -d "e2b.Dockerfile" | tee build_output.txt
          TEMPLATE_ID=$(grep "Requested build for the sandbox template" build_output.txt | awk '{print $NF}')
          echo "Captured Template ID: $TEMPLATE_ID"
          echo "template_id=$TEMPLATE_ID" >> $GITHUB_OUTPUT
          echo "GITHUB_OUTPUT contents:"
          cat $GITHUB_OUTPUT
        working-directory: ./template
        env:
          E2B_ACCESS_TOKEN: ${{ secrets.E2B_ACCESS_TOKEN }}
          E2B_DOMAIN: ${{ inputs.E2B_DOMAIN }}

      - name: Output template ID
        run: |
          echo "Template ID from step output: ${{ steps.build-template.outputs.template_id }}"
          echo "Template ID from job output: ${{ needs.build.outputs.template_id }}"
