name: Test JS SDK

on:
  workflow_call:
    secrets:
      E2B_API_KEY:
        required: true
    inputs:
      E2B_DOMAIN:
        required: false
        type: string
      E2B_TESTS_TEMPLATE:
        required: false
        type: string

permissions:
  contents: read

jobs:
  test:
    defaults:
      run:
        working-directory: ./js
    name: JS SDK - Build and test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 9.5

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Configure pnpm
        run: |
          pnpm config set auto-install-peers true
          pnpm config set exclude-links-from-lockfile true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test build
        run: pnpm build

      - name: Run Node tests
        run: pnpm test
        env:
          E2B_API_KEY: ${{ secrets.E2B_API_KEY }}
          E2B_DOMAIN: ${{ vars.E2B_DOMAIN }}
          E2B_TESTS_TEMPLATE: ${{ inputs.E2B_TESTS_TEMPLATE }}

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15

      - name: Run Bun tests
        run: pnpm test:bun
        env:
          E2B_API_KEY: ${{ secrets.E2B_API_KEY }}
          E2B_DOMAIN: ${{ vars.E2B_DOMAIN }}
          E2B_TESTS_TEMPLATE: ${{ inputs.E2B_TESTS_TEMPLATE }}

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Deno tests
        run: pnpm test:deno
        env:
          E2B_API_KEY: ${{ secrets.E2B_API_KEY }}
          E2B_DOMAIN: ${{ vars.E2B_DOMAIN }}
          E2B_TESTS_TEMPLATE: ${{ inputs.E2B_TESTS_TEMPLATE }}